# Generated by Django 4.2.6 on 2023-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='country_date',
            field=models.DateField(default=True),
        ),
    ]
