# Generated by Django 4.2.6 on 2023-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_capital_country_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='country_date',
            field=models.DateField(default='2020-12-26'),
        ),
    ]
