# Generated by Django 4.2.6 on 2023-12-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_capital_country_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='country_date',
        ),
    ]
